"""
Circuit-card data for every project.  ONE place to keep wiring up to date.

After editing, rebuild the cards:
    python tools/circuit_cards/build.py
GitHub Actions fails the build if docs/ is out of date with this file.

Wire format:  (part_id, part_pin, board_pin, "why, in kid words")
Board pins:   Uno   -> "D0".."D13", "A0".."A5", "5V", "3V3", "GND", "VIN"
              ESP32 -> "D2", "D4", ... "D35", "3V3", "GND", "VIN"
"5V"/"3V3"/"GND" wires automatically move to a breadboard power strip
when the board runs out of those pins.
"""

# --------------------------------------------------------------------------
# Arduino / ESP32 projects
# --------------------------------------------------------------------------
PROJECTS = [
    # ===================== Basics & LEDs =====================
    dict(slug="hello-world", title="Hello World", group="Basics & LEDs",
         folder="arduino/Basics_HelloWorld_Serial", old="HelloWorld", board="uno",
         what="Your board says <b>Hello World</b> on the computer screen every 5 seconds. It's the \"is my board alive?\" test.",
         learn=["Uploading a program", "The Serial Monitor"],
         parts=[], wires=[], serial=9600,
         try_=["Open <b>Tools → Serial Monitor</b> and set it to <b>9600 baud</b>.",
               "Watch \"Hello World\" appear every 5 seconds."],
         tips=[]),
    dict(slug="rgb-color-cycle", title="RGB Color Cycle", group="Basics & LEDs",
         folder="arduino/LED_RGB_ColorCycle", old="TR5", board="uno",
         what="One LED that can glow <b>red, green and blue</b>. It shows each colour for 1 second, again and again.",
         learn=["RGB LEDs have 3 tiny lights inside", "digitalWrite ON / OFF"],
         parts=[dict(id="rgb", type="rgb", label="RGB LED")],
         wires=[("rgb", "R", "D9", "red light"), ("rgb", "G", "D10", "green light"),
                ("rgb", "B", "D11", "blue light"), ("rgb", "−", "GND", "longest leg, ground")],
         try_=["Watch the LED change: red → green → blue."],
         tips=[("Colours in the wrong order?", "Your LED's legs may be in a different order. Swap the R, G, B wires until it matches.", False)]),
    dict(slug="led-scanner", title="LED Scanner", group="Basics & LEDs",
         folder="arduino/LED_Scanner_Buzzer", old="ledunison353", board="uno",
         what="A \"Knight Rider\" light: 3 LEDs sweep left and right across 10 LEDs, and each step plays a music note.",
         learn=["Arrays of pins", "Playing notes with tone()"],
         parts=[dict(id="leds", type="ledrow", label="10 LEDs + 10 resistors"),
                dict(id="bz", type="buzzer_p", label="Passive buzzer")],
         wires=[("leds", str(i - 3), f"D{i}", "LED " + str(i - 3)) for i in range(4, 14)] +
               [("leds", "GND", "GND", "all LED short legs"), ("bz", "+", "D3", "plays the notes"), ("bz", "−", "GND", "ground")],
         try_=["Watch the light sweep and listen to the scale go up and down."],
         tips=[]),
    dict(slug="led-brightness-web-slider", title="LED Brightness from the Web", group="Basics & LEDs", star=True,
         folder="arduino/LED_Brightness_WebSlider", old="(shared in class 2026-08-07)", board="uno",
         what="The board half of the <b>LED From Anywhere</b> demo: a web page slider (0–255) sends a number over USB, and the Uno dims the LED to match. With ngrok, friends anywhere can move the slider.",
         learn=["analogWrite dimming (PWM)", "Reading numbers with Serial.parseInt()", "Arduino + Python + ngrok together"],
         parts=[dict(id="led", type="led", label="LED + 220Ω")],
         wires=[("led", "+", "D11", "brightness 0–255 (a ~ pin can dim)"), ("led", "−", "GND", "ground")], serial=9600,
         python="py-led-slider", showcase=True,
         try_=["Test alone first: open the Serial Monitor at <b>9600 baud</b>, type <code>128</code>, press Enter: half brightness!",
               "Close the Serial Monitor, then run the Python slider page (or double-click <code>DEMO_LED_from_anywhere_Uno_slider.bat</code>)."],
         tips=[]),
    dict(slug="led-light-show", title="LED Light Show (2 buzzers)", group="Basics & LEDs",
         folder="arduino/LED_Scanner_DualBuzzer_Show", old="ledunison123", board="uno",
         what="A 4-part light show on 10 LEDs: sweep, wave, centre burst and blink finale, with sound.",
         learn=["Loops inside loops", "Why an Uno can only play one tone() at a time"],
         parts=[dict(id="leds", type="ledrow", label="10 LEDs + 10 resistors"),
                dict(id="bz1", type="buzzer_p", label="Buzzer 1"),
                dict(id="bz2", type="buzzer_p", label="Buzzer 2")],
         wires=[("leds", str(i - 3), f"D{i}", "LED " + str(i - 3)) for i in range(4, 14)] +
               [("leds", "GND", "GND", "all LED short legs"),
                ("bz1", "+", "D2", "sound 1"), ("bz1", "−", "GND", "ground"),
                ("bz2", "+", "D3", "sound 2"), ("bz2", "−", "GND", "ground")],
         try_=["Watch all 4 acts of the show."],
         tips=[("Buzzer 2 stays quiet", "That's expected: an Uno can play only one tone at a time. It's on the to-do list.", True)]),

    # ===================== Music & Sound =====================
    dict(slug="happy-birthday-serial", title="Happy Birthday on Command", group="Music & Sound",
         folder="arduino/Music_HappyBirthday_Serial", old="Birthday2", board="uno",
         what="Type <b>happy birthday</b> on the computer and the buzzer plays the song.",
         learn=["Reading text from the Serial Monitor", "Notes and durations"],
         parts=[dict(id="bz", type="buzzer_p", label="Passive buzzer")],
         wires=[("bz", "+", "D8", "plays the song"), ("bz", "−", "GND", "ground")], serial=9600,
         try_=["Open the Serial Monitor at <b>9600 baud</b>, line ending <b>Newline</b>.",
               "Type <code>happy birthday</code> and press Enter."],
         tips=[]),
    dict(slug="birthday-light-show", title="Birthday Light Show", group="Music & Sound",
         folder="arduino/Music_HappyBirthday_LEDShow", old="krishbdaytreat454", board="uno",
         what="Plays Happy Birthday while 10 LEDs dance, then a big light-and-sound celebration. Made for Krish's birthday.",
         learn=["Music + lights together", "Functions for each effect"],
         parts=[dict(id="leds", type="ledrow", label="10 LEDs + 10 resistors"),
                dict(id="bz", type="buzzer_p", label="Passive buzzer")],
         wires=[("leds", str(i - 3), f"D{i}", "LED " + str(i - 3)) for i in range(4, 14)] +
               [("leds", "GND", "GND", "all LED short legs"), ("bz", "+", "D3", "plays the song"), ("bz", "−", "GND", "ground")],
         try_=["Power it up and enjoy the show. It repeats every 3 seconds."],
         tips=[]),
    dict(slug="bird-chirps", title="Random Bird Chirps", group="Music & Sound",
         folder="arduino/Sound_RandomBirdChirps", old="birdcalllllls22346454", board="uno",
         what="Two buzzers make natural, random bird chirps, like two birds calling to each other.",
         learn=["random()", "Sweeping a sound up and down"],
         parts=[dict(id="bz1", type="buzzer_p", label="Buzzer 1"), dict(id="bz2", type="buzzer_p", label="Buzzer 2")],
         wires=[("bz1", "+", "D2", "bird 1"), ("bz1", "−", "GND", "ground"),
                ("bz2", "+", "D3", "bird 2"), ("bz2", "−", "GND", "ground")],
         try_=["Put the buzzers far apart and listen to the birds \"talk\"."],
         tips=[("Leave A0 empty", "The program uses the empty pin A0 to make the chirps random.", False)]),
    dict(slug="bird-piano", title="Bird Piano", group="Music & Sound",
         folder="arduino/Sound_BirdPiano_5Buttons", old="birdpiano2345432", board="uno",
         what="Krish's bird communication board: 5 buttons, 5 sparrow calls. Each call means a word: Food, Water, Play, Scritches, Outside.",
         learn=["Reading buttons with INPUT_PULLUP", "Making sounds that feel natural"],
         parts=[dict(id="btn", type="buttons", n=5, label="5 push buttons"),
                dict(id="bz", type="buzzer_p", label="Passive buzzer")],
         wires=[("btn", "1", "D2", "Food"), ("btn", "2", "D3", "Water"), ("btn", "3", "D4", "Play"),
                ("btn", "4", "D5", "Scritches"), ("btn", "5", "D6", "Outside"),
                ("btn", "GND", "GND", "other leg of every button"),
                ("bz", "+", "D9", "plays the call"), ("bz", "−", "GND", "ground")],
         try_=["Press each button and listen: 1 Food, 2 Water, 3 Play, 4 Scritches, 5 Outside."],
         tips=[]),
    dict(slug="clap-detector", title="Clap Detector", group="Music & Sound",
         folder="arduino/Sound_ClapDetect_LED_Buzzer", old="save3", board="uno",
         what="Clap your hands and an LED lights up and a buzzer beeps.",
         learn=["Digital sensors (ON / OFF)", "if / else"],
         parts=[dict(id="mic", type="sound", label="Sound sensor"), dict(id="led", type="led", label="LED + 220Ω"),
                dict(id="bz", type="buzzer_a", label="Active buzzer")],
         wires=[("mic", "DO", "D12", "says \"loud!\""), ("mic", "VCC", "5V", "power"), ("mic", "GND", "GND", "ground"),
                ("led", "+", "D13", "turns the LED on"), ("led", "−", "GND", "ground"),
                ("bz", "+", "D11", "turns the beep on"), ("bz", "−", "GND", "ground")], serial=9600,
         try_=["Clap near the sensor. The LED and buzzer turn on while it's loud."],
         tips=[]),
    dict(slug="clap-mario", title="Clap-Controlled Mario Song", group="Music & Sound",
         folder="arduino/Sound_ClapSensor_MarioMelody", old="buzz6796", board="uno",
         what="Plays the Super Mario theme. The sound sensor starts and stops it.",
         learn=["Playing music without delay() (millis)"],
         parts=[dict(id="mic", type="sound", label="Sound sensor"), dict(id="led", type="led", label="LED + 220Ω"),
                dict(id="bz", type="buzzer_p", label="Passive buzzer")],
         wires=[("mic", "DO", "D12", "sensor signal"), ("mic", "VCC", "5V", "power"), ("mic", "GND", "GND", "ground"),
                ("led", "+", "D13", "LED on while music plays"), ("led", "−", "GND", "ground"),
                ("bz", "+", "D8", "plays the song"), ("bz", "−", "GND", "ground")], serial=9600,
         try_=["Clap or stay quiet and see when the music plays."],
         tips=[("Works the opposite way?", "Some sound sensors send HIGH when quiet. That's a known question in the to-do list.", True)]),
    dict(slug="loudness-alarm", title="Loudness Alarm", group="Music & Sound",
         folder="arduino/Sound_LoudnessAlarm_Analog", old="soundtime55fun", board="uno",
         what="Measures how loud it is (0–1023) and beeps when the number reaches 625.",
         learn=["Analog sensors give a number", "analogRead()"],
         parts=[dict(id="mic", type="sound", label="Sound sensor"), dict(id="led", type="led", label="LED + 220Ω"),
                dict(id="bz", type="buzzer_a", label="Active buzzer")],
         wires=[("mic", "AO", "A0", "sends the loudness number"), ("mic", "VCC", "5V", "power"), ("mic", "GND", "GND", "ground"),
                ("led", "+", "D13", "flash"), ("led", "−", "GND", "ground"),
                ("bz", "+", "D11", "beep"), ("bz", "−", "GND", "ground")], serial=9600,
         try_=["Open the Serial Monitor at <b>9600 baud</b> and watch the number.", "Make a loud sound for about a second."],
         tips=[("Misses short claps", "It only listens once per second. That's on the to-do list.", True)]),

    # ===================== Sensors & Security =====================
    dict(slug="night-light", title="Automatic Night Light", group="Sensors & Security",
         folder="arduino/Sensor_AutoNightLight_LDR", old="nightligt6700", board="uno",
         what="A light sensor sets an LED to <b>full, half or off</b> depending on how dark the room is.",
         learn=["Light sensors (LDR)", "analogWrite for brightness"],
         parts=[dict(id="ldr", type="ldr", label="Light sensor (LDR) + 10kΩ"), dict(id="led", type="led", label="LED + 220Ω")],
         wires=[("ldr", "VCC", "5V", "LDR leg to power"), ("ldr", "OUT", "A0", "middle point, the light number"),
                ("ldr", "GND", "GND", "10kΩ leg to ground"),
                ("led", "+", "D11", "brightness control"), ("led", "−", "GND", "ground")], serial=9600,
         try_=["Cover the light sensor with your hand. The LED gets brighter."],
         tips=[("Very dark does nothing", "Readings below 650 are skipped by the program. It's on the to-do list.", True)]),
    dict(slug="parking-sensor", title="Parking Sensor", group="Sensors & Security",
         folder="arduino/Sensor_ParkingSensor_Ultrasonic", old="car33", board="uno",
         what="Beeps faster as something gets closer, like the sensor on the back of a car.",
         learn=["How ultrasonic sensors measure distance", "if / else if"],
         parts=[dict(id="us", type="hcsr04", label="Distance sensor HC-SR04"), dict(id="bz", type="buzzer_a", label="Active buzzer")],
         wires=[("us", "VCC", "5V", "power for the sensor"), ("us", "GND", "GND", "ground"),
                ("us", "TRIG", "D9", "Uno says \"send a sound now!\""), ("us", "ECHO", "D10", "how long the echo took"),
                ("bz", "+", "D13", "turns the beep on and off"), ("bz", "−", "GND", "ground")], serial=9600,
         try_=["Move your hand slowly toward the sensor. Far away: quiet. Closer: faster beeps. Very close: nonstop beep."],
         tips=[("Beeps all the time", "With nothing in front, the program thinks it is 0 cm. Point it at a wall about 1 m away. It's on the to-do list.", True)]),
    dict(slug="object-removed-alarm", title="Object Removed Alarm", group="Sensors & Security",
         folder="arduino/Security_ObjectRemovedAlarm", old="steal777", board="uno",
         what="Put something valuable in front of the sensor. If someone takes it, the alarm beeps!",
         learn=["Using distance as a security guard"],
         parts=[dict(id="us", type="hcsr04", label="Distance sensor HC-SR04"), dict(id="bz", type="buzzer_a", label="Active buzzer")],
         wires=[("us", "VCC", "5V", "power"), ("us", "GND", "GND", "ground"),
                ("us", "TRIG", "D9", "send sound"), ("us", "ECHO", "D10", "hear echo"),
                ("bz", "+", "D8", "alarm beep"), ("bz", "−", "GND", "ground")], serial=9600,
         try_=["Put a box about 5 cm in front of the sensor. Take it away: beep beep!"],
         tips=[]),
    dict(slug="night-theft-alarm", title="Night Theft Alarm", group="Sensors & Security",
         folder="arduino/Security_NightTheftAlarm", old="seal888", board="uno",
         what="At night it turns on a street light and guards your object. In the day the alarm is off.",
         learn=["Combining two sensors", "Day / evening / night modes"],
         parts=[dict(id="ldr", type="ldr", label="Light sensor (LDR) + 10kΩ"), dict(id="led", type="led", label="Street light LED + 220Ω"),
                dict(id="us", type="hcsr04", label="Distance sensor HC-SR04"), dict(id="bz", type="buzzer_a", label="Active buzzer")],
         wires=[("ldr", "VCC", "5V", "power"), ("ldr", "OUT", "A0", "light number"), ("ldr", "GND", "GND", "ground"),
                ("led", "+", "D11", "street light"), ("led", "−", "GND", "ground"),
                ("us", "VCC", "5V", "power"), ("us", "GND", "GND", "ground"),
                ("us", "TRIG", "D9", "send sound"), ("us", "ECHO", "D10", "hear echo"),
                ("bz", "+", "D13", "alarm"), ("bz", "−", "GND", "ground")], serial=9600,
         try_=["Cover the light sensor (night). Now take the object away: alarm!"],
         tips=[]),
    dict(slug="police-siren-theft-detector", title="Theft Detector with Police Siren", group="Sensors & Security",
         folder="arduino/Security_TheftDetector_PoliceSiren", old="final12345", board="uno",
         what="The best version of the alarm: at night, if your object is taken, a police siren wails with flashing red and blue lights.",
         learn=["Sirens with tone() sweeps", "Helper functions"],
         parts=[dict(id="ldr", type="ldr", label="Light sensor (LDR) + 10kΩ"), dict(id="led", type="led", label="Street light LED + 220Ω"),
                dict(id="rgb", type="rgb", label="RGB LED (red + blue)"), dict(id="us", type="hcsr04", label="Distance sensor HC-SR04"),
                dict(id="bz", type="buzzer_p", label="Passive buzzer")],
         wires=[("ldr", "VCC", "5V", "power"), ("ldr", "OUT", "A0", "light number"), ("ldr", "GND", "GND", "ground"),
                ("led", "+", "D11", "street light"), ("led", "−", "GND", "ground"),
                ("rgb", "R", "D4", "red flash"), ("rgb", "B", "D5", "blue flash"), ("rgb", "−", "GND", "ground"),
                ("us", "VCC", "5V", "power"), ("us", "GND", "GND", "ground"),
                ("us", "TRIG", "D9", "send sound"), ("us", "ECHO", "D10", "hear echo"),
                ("bz", "+", "D13", "siren"), ("bz", "−", "GND", "ground")], serial=9600,
         try_=["Cover the light sensor so it's \"night\".", "Take the object away from the sensor and hear the siren."],
         tips=[("Siren only chirps", "It checks every 3 seconds, so the siren is short. It's on the to-do list.", True)]),

    # ===================== Doors =====================
    dict(slug="button-door", title="Button Door", group="Doors",
         folder="arduino/Door_Servo_ButtonOpen", old="Sweep", board="uno",
         what="Press a button and a motor opens a little door slowly, waits 5 seconds, then closes it.",
         learn=["Servo motors move to an angle", "Buttons"],
         parts=[dict(id="sv", type="servo", label="Servo motor SG90"), dict(id="btn", type="button", label="Push button")],
         wires=[("sv", "SIG", "D10", "tells the motor the angle"), ("sv", "5V", "5V", "power (red wire)"), ("sv", "GND", "GND", "ground (brown wire)"),
                ("btn", "leg 1", "D9", "the Uno reads the button"), ("btn", "leg 2", "GND", "ground")], serial=9600,
         libs=["Servo"],
         try_=["Press the button. The door opens, waits 5 seconds and closes."],
         tips=[]),
    dict(slug="rfid-door", title="RFID Card Door Lock", group="Doors",
         folder="arduino/Door_RFID_AccessControl", old="entercard12345", board="uno",
         what="Tap the right card and the door opens with a happy beep. A wrong card gets a warning buzz.",
         learn=["RFID cards have an ID number", "SPI connections"],
         parts=[dict(id="rf", type="rc522", label="RFID reader RC522"), dict(id="sv", type="servo", label="Servo motor SG90"),
                dict(id="bz", type="buzzer_p", label="Passive buzzer")],
         wires=[("rf", "SDA", "D10", "chip select"), ("rf", "SCK", "D13", "clock"), ("rf", "MOSI", "D11", "Uno → reader"),
                ("rf", "MISO", "D12", "reader → Uno"), ("rf", "RST", "D9", "reset"),
                ("rf", "3.3V", "3V3", "3.3V ONLY, never 5V!"), ("rf", "GND", "GND", "ground"),
                ("sv", "SIG", "D6", "door angle"), ("sv", "5V", "5V", "power"), ("sv", "GND", "GND", "ground"),
                ("bz", "+", "D3", "beeps"), ("bz", "−", "GND", "ground")], serial=9600,
         libs=["MFRC522", "Servo"],
         try_=["Open the Serial Monitor at <b>9600 baud</b>.", "Tap a card: the Serial Monitor shows its ID. Only the saved card opens the door."],
         tips=[("RFID reader: 3.3V only", "The RC522 is damaged by 5V. Use the Uno's 3.3V pin.", True),
               ("Add your own card", "Copy the card ID from the Serial Monitor into <code>authorizedUID</code> in the program.", False)]),

    # ===================== IR remote, LCD & displays =====================
    dict(slug="ir-code-reader", title="IR Remote Code Reader", group="IR Remote & Displays",
         folder="arduino/IR_RemoteCodeReader", old="IRHEX123", board="uno",
         what="Press any button on the remote and its secret code appears on the computer.",
         learn=["Infrared light (invisible!)", "Libraries"],
         parts=[dict(id="ir", type="ir", label="IR receiver")],
         wires=[("ir", "OUT", "D2", "sends the remote's code"), ("ir", "VCC", "5V", "power"), ("ir", "GND", "GND", "ground")], serial=9600,
         libs=["IRremote"],
         try_=["Open the Serial Monitor at <b>9600 baud</b>.", "Point the remote at the receiver and press buttons."],
         tips=[]),
    dict(slug="ir-remote-lcd", title="IR Remote on LCD", group="IR Remote & Displays",
         folder="arduino/IR_RemoteButtons_LCD", old="remoteHEXir34", board="uno",
         what="Press a remote button and its name (POWER, VOL+, 1, 2…) shows on the screen.",
         learn=["switch / case", "I2C screens use only 2 wires"],
         parts=[dict(id="ir", type="ir", label="IR receiver"), dict(id="lcd", type="lcd", label="16×2 LCD (I2C)")],
         wires=[("ir", "OUT", "D2", "remote codes"), ("ir", "VCC", "5V", "power"), ("ir", "GND", "GND", "ground"),
                ("lcd", "SDA", "A4", "data (I2C)"), ("lcd", "SCL", "A5", "clock (I2C)"),
                ("lcd", "VCC", "5V", "power"), ("lcd", "GND", "GND", "ground")], serial=9600,
         libs=["IRremote", "LiquidCrystal I2C"],
         try_=["Press buttons on the remote and read the screen."],
         tips=[]),
    dict(slug="lcd-message-board", title="LCD Message Board", group="IR Remote & Displays",
         folder="arduino/LCD_SerialMessageBoard", old="LCDMSG25434", board="uno",
         what="Type a message on the computer and it appears on the little screen.",
         learn=["Sending text to a screen"],
         parts=[dict(id="lcd", type="lcd", label="16×2 LCD (I2C)")],
         wires=[("lcd", "SDA", "A4", "data (I2C)"), ("lcd", "SCL", "A5", "clock (I2C)"),
                ("lcd", "VCC", "5V", "power"), ("lcd", "GND", "GND", "ground")], serial=9600,
         libs=["LiquidCrystal I2C"],
         try_=["Open the Serial Monitor at <b>9600 baud</b>, line ending <b>Newline</b>.", "Type a message (up to 32 letters) and press Enter."],
         tips=[]),
    dict(slug="led-matrix-k", title="LED Matrix Letter K", group="IR Remote & Displays",
         folder="arduino/Display_LEDMatrix_LetterK", old="matrix15678423", board="uno",
         what="Draws the letter <b>K</b> on an 8×8 grid of red LEDs.",
         learn=["Pictures made of 1s and 0s (bitmaps)"],
         parts=[dict(id="mx", type="max7219", label="8×8 LED matrix MAX7219")],
         wires=[("mx", "VCC", "5V", "power"), ("mx", "GND", "GND", "ground"),
                ("mx", "DIN", "D12", "picture data"), ("mx", "CS", "D10", "\"listen now\""), ("mx", "CLK", "D11", "clock")],
         libs=["LedControl"],
         try_=["Power it up and see the letter K."],
         tips=[]),
    dict(slug="hana-mini-tv", title="Hana Mini TV", group="IR Remote & Displays",
         folder="arduino/Project_HanaMiniTV_IR_LCD", old="minitv1245", board="uno", star=True,
         what="A pretend TV! Use the remote to switch between 9 channels of animations and mini-games on the little screen.",
         learn=["Custom LCD characters", "Big programs split into functions"],
         parts=[dict(id="ir", type="ir", label="IR receiver"), dict(id="bz", type="buzzer_p", label="Passive buzzer"),
                dict(id="lcd", type="lcd", label="16×2 LCD (I2C)")],
         wires=[("ir", "OUT", "D2", "remote codes"), ("ir", "VCC", "5V", "power"), ("ir", "GND", "GND", "ground"),
                ("bz", "+", "D8", "beeps"), ("bz", "−", "GND", "ground"),
                ("lcd", "SDA", "A4", "data (I2C)"), ("lcd", "SCL", "A5", "clock (I2C)"),
                ("lcd", "VCC", "5V", "power"), ("lcd", "GND", "GND", "ground")], serial=9600,
         libs=["IRremote", "LiquidCrystal I2C"],
         try_=["Press <b>POWER</b> on the remote: \"Hana TV Welcomes you!\"", "Press <b>1</b> to <b>9</b> to change channel. Try 2 (Dino game)!"],
         tips=[]),

    # ===================== Games =====================
    dict(slug="flappy-bird-lcd", title="Flappy Bird (LCD)", group="Games",
         folder="arduino/Game_FlappyBird_LCD", old="flappybird0000", board="uno",
         what="Flappy Bird on a tiny screen. Push the joystick up to flap through the pipes.",
         learn=["Game loops", "Joysticks give numbers"],
         parts=[dict(id="lcd", type="lcd", label="16×2 LCD (I2C)"), dict(id="js", type="joystick", label="Joystick")],
         wires=[("lcd", "SDA", "A4", "data (I2C)"), ("lcd", "SCL", "A5", "clock (I2C)"),
                ("lcd", "VCC", "5V", "power"), ("lcd", "GND", "GND", "ground"),
                ("js", "VRy", "A1", "up / down"), ("js", "SW", "D3", "click = restart"),
                ("js", "+5V", "5V", "power"), ("js", "GND", "GND", "ground")],
         libs=["LiquidCrystal I2C"],
         try_=["Push the joystick up to flap. Click it to play again after a crash."],
         tips=[]),
    dict(slug="sky-guardian-lcd", title="Sky Guardian (LCD)", group="Games",
         folder="arduino/Game_SkyGuardian_LCD", old="skyguard13455", board="uno",
         what="The first eagle game: fly with the joystick and shoot bugs before they steal your eggs.",
         learn=["Moving many objects", "Structs"],
         parts=[dict(id="lcd", type="lcd", label="16×2 LCD (I2C)"), dict(id="js", type="joystick", label="Joystick"),
                dict(id="b1", type="button", label="Long-shot button"), dict(id="b2", type="button", label="Short-shot button"),
                dict(id="bz", type="buzzer_p", label="Passive buzzer")],
         wires=[("lcd", "SDA", "A4", "data (I2C)"), ("lcd", "SCL", "A5", "clock (I2C)"),
                ("lcd", "VCC", "5V", "power"), ("lcd", "GND", "GND", "ground"),
                ("js", "VRx", "A0", "left / right"), ("js", "VRy", "A1", "up / down"), ("js", "SW", "D3", "click = start"),
                ("js", "+5V", "5V", "power"), ("js", "GND", "GND", "ground"),
                ("b1", "leg 1", "D8", "long feather"), ("b1", "leg 2", "GND", "ground"),
                ("b2", "leg 1", "D9", "short feather"), ("b2", "leg 2", "GND", "ground"),
                ("bz", "+", "D13", "sound effects"), ("bz", "−", "GND", "ground")],
         libs=["LiquidCrystal I2C"],
         try_=["Click the joystick to start. Move, and shoot with the two buttons."],
         tips=[]),
    dict(slug="sky-guard-tft", title="Sky Guard TFT", group="Games",
         folder="arduino/SkyGuardTFT", old="SkyGuardTFT", board="esp32", star=True,
         what="The big arcade game on a colour screen: an eagle with 4 feather weapons and a loop-the-loop grab defends its nest.",
         learn=["Colour graphics", "ESP32 boards", "Saving a best score"],
         parts=[dict(id="tft", type="st7789", label="1.54\" colour screen ST7789"),
                dict(id="js", type="joystick", label="Joystick"),
                dict(id="btn", type="buttons", n=5, label="5 buttons"),
                dict(id="bz", type="buzzer_p", label="Passive buzzer")],
         wires=[("tft", "SCL", "D18", "clock"), ("tft", "SDA", "D23", "picture data"), ("tft", "RES", "D4", "reset"),
                ("tft", "DC", "D2", "data or command"), ("tft", "CS", "D5", "\"listen now\""),
                ("tft", "VCC", "3V3", "power 3.3V"), ("tft", "BLK", "3V3", "backlight 3.3V"), ("tft", "GND", "GND", "ground"),
                ("js", "VRx", "D34", "left / right"), ("js", "VRy", "D35", "up / down"), ("js", "SW", "D32", "talon flip"),
                ("js", "+5V", "3V3", "use 3.3V, NOT 5V!"), ("js", "GND", "GND", "ground"),
                ("btn", "1", "D13", "short feather"), ("btn", "2", "D14", "long feather"), ("btn", "3", "D27", "fire feather"),
                ("btn", "4", "D26", "electric feather"), ("btn", "5", "D22", "pause"), ("btn", "GND", "GND", "other leg of every button"),
                ("bz", "+", "D25", "sound"), ("bz", "−", "GND", "ground")], serial=115200,
         libs=["Adafruit ST7735 and ST7789", "Adafruit GFX"],
         try_=["Don't touch the joystick while it starts (it's measuring the middle).", "Click the joystick to start. Buttons 1–4 shoot, 5 pauses."],
         tips=[("Blank screen?", "Run the <b>Screen Wiring Finder</b> and <b>Screen Health Check</b> tools.", False),
               ("One-click upload", "Double-click <code>Upload to ESP32.bat</code> in the project folder.", False)]),

    # ===================== Smart House =====================
    dict(slug="smart-house", title="Smart House", group="Smart House", star=True,
         folder="arduino/SmartHouse_v1", old="Smarthousev1wrking", board="uno",
         what="A model smart house: automatic door, temperature screen, night light, party mode with music, bedtime with an intruder alarm, and a mini game. You control it by typing commands.",
         learn=["Modes", "Many parts on one board", "Music stored in flash memory"],
         parts=[dict(id="lcd", type="lcd", label="16×2 LCD (I2C)"), dict(id="dht", type="dht11", label="Temperature sensor DHT11"),
                dict(id="ldr", type="ldr", label="Light sensor (LDR) + 10kΩ"),
                dict(id="sv", type="servo", label="Door servo SG90"), dict(id="us", type="hcsr04", label="Distance sensor HC-SR04"),
                dict(id="rgb", type="rgb", label="RGB LED"), dict(id="led", type="led", label="Night light LED + 220Ω"),
                dict(id="btn", type="button", label="Door button"), dict(id="bzp", type="buzzer_p", label="Passive buzzer (music)"),
                dict(id="bza", type="buzzer_a", label="Active buzzer (optional)")],
         wires=[("sv", "SIG", "D2", "door angle"), ("sv", "5V", "5V", "power"), ("sv", "GND", "GND", "ground"),
                ("us", "TRIG", "D3", "send sound"), ("us", "ECHO", "D4", "hear echo"), ("us", "VCC", "5V", "power"), ("us", "GND", "GND", "ground"),
                ("bza", "+", "D5", "not used by the program yet"), ("bza", "−", "GND", "ground"),
                ("rgb", "R", "D7", "red"), ("rgb", "G", "D8", "green"), ("rgb", "B", "D9", "blue"), ("rgb", "−", "GND", "ground"),
                ("bzp", "+", "D10", "music"), ("bzp", "−", "GND", "ground"),
                ("led", "+", "D11", "night light"), ("led", "−", "GND", "ground"),
                ("btn", "leg 1", "D12", "door button"), ("btn", "leg 2", "GND", "ground"),
                ("ldr", "OUT", "A0", "light number"), ("ldr", "VCC", "5V", "power"), ("ldr", "GND", "GND", "ground"),
                ("dht", "DATA", "A3", "temperature"), ("dht", "VCC", "5V", "power"), ("dht", "GND", "GND", "ground"),
                ("lcd", "SDA", "A4", "data (I2C)"), ("lcd", "SCL", "A5", "clock (I2C)"), ("lcd", "VCC", "5V", "power"), ("lcd", "GND", "GND", "ground")],
         serial=9600, libs=["LiquidCrystal I2C", "Servo", "DHT sensor library"],
         try_=["Open the Serial Monitor at <b>9600 baud</b>, line ending <b>Newline</b>.",
               "Type <code>help</code>, then try <code>party</code>, <code>bedtime</code>, <code>gamemode</code>, <code>normal</code>."],
         tips=[("Big build: go slowly", "Connect one part, test it, then add the next. The learning sketches in this folder test each part alone.", False)]),

    # ===================== ESP32 & Tools =====================
    dict(slug="esp32-wifi-led", title="ESP32 Wi-Fi LED", group="ESP32 & Tools",
         folder="arduino/ESP32_WiFi_LED_WebAPI", old="ESP32_api", board="esp32",
         what="The ESP32 joins your Wi-Fi. Open a web address on a phone to turn its LED on and off.",
         learn=["Wi-Fi and web servers", "Keeping passwords secret"],
         parts=[], wires=[], builtin_led="D2", serial=9600, secrets=True,
         python="py-esp32-led-control", showcase=True, star=True,
         try_=["Open the Serial Monitor at <b>9600 baud</b> and write down the IP address, e.g. <code>192.168.1.42</code>.",
               "On a phone on the same Wi-Fi, open <code>http://192.168.1.42/on</code>, then <code>/off</code>, then <code>/bird</code>."],
         tips=[("Stuck printing dots", "The Wi-Fi name or password in <code>arduino_secrets.h</code> is wrong.", False)]),
    dict(slug="i2c-scanner", title="I2C Scanner (tool)", group="ESP32 & Tools",
         folder="arduino/Tool_I2C_Scanner", old="i2cfind3456", board="uno",
         what="A detective tool: finds the address of any I2C screen or sensor. Use it when an LCD stays blank.",
         learn=["Every I2C device has an address"],
         parts=[dict(id="lcd", type="lcd", label="Any I2C device (e.g. LCD)")],
         wires=[("lcd", "SDA", "A4", "data (I2C)"), ("lcd", "SCL", "A5", "clock (I2C)"),
                ("lcd", "VCC", "5V", "power"), ("lcd", "GND", "GND", "ground")], serial=9600,
         try_=["Open the Serial Monitor at <b>9600 baud</b> and press RESET on the Uno.",
               "Read the address: LCD = <b>0x27</b> or <b>0x3F</b>, MPU6050 = <b>0x68</b>."],
         tips=[]),
    dict(slug="screen-wiring-finder", title="Screen Wiring Finder (tool)", group="ESP32 & Tools",
         folder="arduino/Tool_ST7789_WiringFinder", old="TFTTest", board="esp32",
         what="If the colour screen stays dark, this tool tries the right wiring and 5 common mix-ups. The TEST number that lights up tells you what to fix.",
         learn=["Debugging step by step"],
         parts=[dict(id="tft", type="st7789", label="1.54\" colour screen ST7789")],
         wires=[("tft", "SCL", "D18", "clock"), ("tft", "SDA", "D23", "data"), ("tft", "RES", "D4", "reset"),
                ("tft", "DC", "D2", "data or command"), ("tft", "CS", "D5", "\"listen now\""),
                ("tft", "VCC", "3V3", "power 3.3V"), ("tft", "BLK", "3V3", "backlight"), ("tft", "GND", "GND", "ground")], serial=115200,
         libs=["Adafruit ST7735 and ST7789", "Adafruit GFX"],
         try_=["Watch the screen: which <b>TEST</b> number shows up?", "Serial Monitor at <b>115200 baud</b> says what that test means."],
         tips=[]),
    dict(slug="screen-health-check", title="Screen Health Check (tool)", group="ESP32 & Tools",
         folder="arduino/Tool_ST7789_HealthCheck", old="TFTCheck", board="esp32",
         what="Asks the colour screen \"are you alive?\" and prints the answer in plain English.",
         learn=["Testing hardware"],
         parts=[dict(id="tft", type="st7789", label="1.54\" colour screen ST7789")],
         wires=[("tft", "SCL", "D18", "clock"), ("tft", "SDA", "D23", "data"), ("tft", "RES", "D4", "reset"),
                ("tft", "DC", "D2", "data or command"), ("tft", "CS", "D5", "\"listen now\""),
                ("tft", "VCC", "3V3", "power 3.3V"), ("tft", "BLK", "3V3", "backlight"), ("tft", "GND", "GND", "ground")], serial=115200,
         libs=["Adafruit ST7735 and ST7789", "Adafruit GFX"],
         try_=["Open the Serial Monitor at <b>115200 baud</b>, press EN on the ESP32, and read the RESULT."],
         tips=[]),
    dict(slug="button-to-keypress", title="Button to Keyboard", group="ESP32 & Tools",
         folder="arduino/Input_Button_SerialEvent", old="keyboard2345", board="uno",
         what="Press a button on the breadboard and the computer types <b>=</b>. It needs the Python program too.",
         learn=["Debouncing buttons", "Arduino + Python working together"],
         parts=[dict(id="btn", type="button", label="Push button")],
         wires=[("btn", "leg 1", "D11", "the Uno reads the button"), ("btn", "leg 2", "GND", "ground")], serial=9600,
         python="py-serial-button-keypress",
         try_=["Upload, then <b>close the Serial Monitor</b>.", "Run the Python program <code>serial_button_to_keypress.py</code>, open Calculator, press the button."],
         tips=[]),
    dict(slug="wip-bird", title="Bird (not started)", group="ESP32 & Tools",
         folder="arduino/WIP_Bird_Empty", old="Bird.sep26", board="uno", wip=True,
         what="A new bird project that hasn't been started yet. The program file is empty.",
         learn=[], parts=[], wires=[], try_=[], tips=[]),
]

# --------------------------------------------------------------------------
# Smart House learning sketches (inside arduino/SmartHouse_v1/)
# --------------------------------------------------------------------------
SH = "arduino/SmartHouse_v1/"
LEARNING = [
    dict(slug="l-jun14a-lcd-name", title="Jun 14a · LCD Shows a Name", folder=SH + "Jun14a_LCD_I2C_PrintName", old="sketch_jun14a", board="uno",
         what="Writes a name on the little screen.", parts=[dict(id="lcd", type="lcd", label="16×2 LCD (I2C)")],
         wires=[("lcd", "SDA", "A4", "data"), ("lcd", "SCL", "A5", "clock"), ("lcd", "VCC", "5V", "power"), ("lcd", "GND", "GND", "ground")],
         libs=["LiquidCrystal I2C"], try_=["See the name on the screen."]),
    dict(slug="l-jun14b-rgb-fade", title="Jun 14b · RGB Fade", folder=SH + "Jun14b_LED_RGB_FadeEachColor", old="sketch_jun14b", board="uno",
         what="Red, then green, then blue fade in and out.", parts=[dict(id="rgb", type="rgb", label="RGB LED")],
         wires=[("rgb", "R", "D9", "red"), ("rgb", "G", "D10", "green"), ("rgb", "B", "D11", "blue"), ("rgb", "−", "GND", "ground")],
         try_=["Watch each colour glow and fade."]),
    dict(slug="l-jun14d-fade-5", title="Jun 14d · Fade 5 Times", folder=SH + "Jun14d_LED_Fade_5Times", old="sketch_jun14d", board="uno",
         what="An LED fades in and out 5 times, then stops.", parts=[dict(id="led", type="led", label="LED + 220Ω")],
         wires=[("led", "+", "D11", "brightness"), ("led", "−", "GND", "ground")], try_=["Count the 5 fades. Press RESET to see it again."]),
    dict(slug="l-jun14e-fade-forever", title="Jun 14e · Breathing LED", folder=SH + "Jun14e_LED_Fade_Forever", old="sketch_jun14e", board="uno",
         what="An LED fades in and out forever, like breathing.", parts=[dict(id="led", type="led", label="LED + 220Ω")],
         wires=[("led", "+", "D10", "brightness"), ("led", "−", "GND", "ground")], try_=["Watch the LED breathe."]),
    dict(slug="l-jun15a-rgb-3-rounds", title="Jun 15a · RGB Fade × 3", folder=SH + "Jun15a_LED_RGB_Fade_3Rounds", old="sketch_jun15a", board="uno",
         what="The RGB fade runs 3 rounds each loop.", parts=[dict(id="rgb", type="rgb", label="RGB LED")],
         wires=[("rgb", "R", "D9", "red"), ("rgb", "G", "D10", "green"), ("rgb", "B", "D11", "blue"), ("rgb", "−", "GND", "ground")],
         try_=["Watch the colours fade."]),
    dict(slug="l-jun16a-birthday", title="Jun 16a · Happy Birthday", folder=SH + "Jun16a_Music_HappyBirthday_Serial", old="sketch_jun16a", board="uno",
         what="Type happy birthday to play the song.", parts=[dict(id="bz", type="buzzer_p", label="Passive buzzer")],
         wires=[("bz", "+", "D8", "music"), ("bz", "−", "GND", "ground")], serial=9600,
         try_=["Serial Monitor at 9600, Newline. Type <code>happy birthday</code>."]),
    dict(slug="l-jun16c-led-on-off", title="Jun 16c · Type ON / OFF", folder=SH + "Jun16c_LED_SerialOnOff", old="sketch_jun16c", board="uno",
         what="Type ON or OFF to switch an LED. The Uno's own \"L\" LED works too, with no wires!", parts=[dict(id="led", type="led", label="LED + 220Ω (optional)")],
         wires=[("led", "+", "D13", "on / off"), ("led", "−", "GND", "ground")], serial=9600,
         try_=["Serial Monitor at 9600, Newline. Type <code>ON</code>, then <code>OFF</code>."]),
    dict(slug="l-jun17a-clap", title="Jun 17a · Clap Detect", folder=SH + "Jun17a_Sound_ClapDetect_Serial", old="sketch_jun17a", board="uno",
         what="Prints \"Clap Detected\" when you clap.", parts=[dict(id="mic", type="sound", label="Sound sensor")],
         wires=[("mic", "DO", "D12", "loud signal"), ("mic", "VCC", "5V", "power"), ("mic", "GND", "GND", "ground")], serial=9600,
         try_=["Serial Monitor at 9600. Clap!"]),
    dict(slug="l-jun17b-clap-led", title="Jun 17b · Clap Light", folder=SH + "Jun17b_Sound_ClapDetect_LED", old="sketch_jun17b", board="uno",
         what="The LED lights while it's loud.", parts=[dict(id="mic", type="sound", label="Sound sensor"), dict(id="led", type="led", label="LED + 220Ω")],
         wires=[("mic", "DO", "D12", "loud signal"), ("mic", "VCC", "5V", "power"), ("mic", "GND", "GND", "ground"),
                ("led", "+", "D13", "light"), ("led", "−", "GND", "ground")], serial=9600, try_=["Clap and watch the LED."]),
    dict(slug="l-jun18b-double-clap-beep", title="Jun 18b · Double Clap Beep", folder=SH + "Jun18b_Sound_DoubleClap_Beeps", old="sketch_jun18b", board="uno",
         what="Clap twice quickly and the buzzer goes beep-beep-beeeep.",
         parts=[dict(id="mic", type="sound", label="Sound sensor"), dict(id="led", type="led", label="LED + 220Ω"), dict(id="bz", type="buzzer_a", label="Active buzzer")],
         wires=[("mic", "DO", "D12", "loud signal"), ("mic", "VCC", "5V", "power"), ("mic", "GND", "GND", "ground"),
                ("led", "+", "D13", "first clap"), ("led", "−", "GND", "ground"), ("bz", "+", "D11", "beeps"), ("bz", "−", "GND", "ground")],
         serial=9600, try_=["Clap twice within 1.5 seconds."]),
    dict(slug="l-jun18d-double-clap-tune", title="Jun 18d · Double Clap Tune", folder=SH + "Jun18d_Sound_DoubleClap_Melody", old="sketch_jun18d", board="uno",
         what="Clap twice quickly and it plays a little tune.",
         parts=[dict(id="mic", type="sound", label="Sound sensor"), dict(id="led", type="led", label="LED + 220Ω"), dict(id="bz", type="buzzer_p", label="Passive buzzer")],
         wires=[("mic", "DO", "D12", "loud signal"), ("mic", "VCC", "5V", "power"), ("mic", "GND", "GND", "ground"),
                ("led", "+", "D13", "first clap"), ("led", "−", "GND", "ground"), ("bz", "+", "D11", "tune"), ("bz", "−", "GND", "ground")],
         serial=9600, try_=["Clap twice within 1.5 seconds."]),
    dict(slug="l-jun18e-sound-number", title="Jun 18e · Sound Number", folder=SH + "Jun18e_Sound_AnalogLevel_Serial", old="sketch_jun18e", board="uno",
         what="Shows how loud it is as a number, once a second.", parts=[dict(id="mic", type="sound", label="Sound sensor")],
         wires=[("mic", "AO", "A0", "loudness number"), ("mic", "VCC", "5V", "power"), ("mic", "GND", "GND", "ground")], serial=9600,
         try_=["Serial Monitor at 9600. Talk, whisper, clap: watch the number."]),
    dict(slug="l-jun19a-object-alarm", title="Jun 19a · Object Alarm", folder=SH + "Jun19a_Ultrasonic_ObjectRemovedAlarm", old="sketch_jun19a", board="uno",
         what="Beeps if the object in front of the sensor is taken away.",
         parts=[dict(id="us", type="hcsr04", label="Distance sensor HC-SR04"), dict(id="bz", type="buzzer_a", label="Active buzzer")],
         wires=[("us", "VCC", "5V", "power"), ("us", "GND", "GND", "ground"), ("us", "TRIG", "D9", "send sound"), ("us", "ECHO", "D10", "hear echo"),
                ("bz", "+", "D13", "alarm"), ("bz", "−", "GND", "ground")], serial=9600, try_=["Put an object 3 cm away, then take it."]),
    dict(slug="l-jun19c-distance", title="Jun 19c · Measure Distance", folder=SH + "Jun19c_Ultrasonic_Distance_Serial", old="sketch_jun19c", board="uno",
         what="Shows the distance in cm, once a second.", parts=[dict(id="us", type="hcsr04", label="Distance sensor HC-SR04")],
         wires=[("us", "VCC", "5V", "power"), ("us", "GND", "GND", "ground"), ("us", "TRIG", "D9", "send sound"), ("us", "ECHO", "D10", "hear echo")],
         serial=9600, try_=["Serial Monitor at 9600. Move your hand closer and farther."]),
    dict(slug="l-jun22b-light-number", title="Jun 22b · Light Number", folder=SH + "Jun22b_LDR_Light_Serial", old="sketch_jun22b", board="uno",
         what="Shows how bright the room is, as a number.", parts=[dict(id="ldr", type="ldr", label="Light sensor (LDR) + 10kΩ")],
         wires=[("ldr", "VCC", "5V", "power"), ("ldr", "OUT", "A0", "light number"), ("ldr", "GND", "GND", "ground")], serial=9600,
         try_=["Serial Monitor at 9600. Cover the sensor, then shine a torch on it."]),
    dict(slug="l-jun24a-motion", title="Jun 24a · Motion Detector", folder=SH + "Jun24a_PIR_Motion_Serial", old="sketch_jun24a", board="uno",
         what="Prints \"Motion Detected!\" when someone moves.", parts=[dict(id="pir", type="pir", label="Motion sensor PIR")],
         wires=[("pir", "OUT", "D5", "motion signal"), ("pir", "VCC", "5V", "power"), ("pir", "GND", "GND", "ground")], serial=9600,
         try_=["Wait 1 minute after plugging in. Then wave your hand."]),
    dict(slug="l-jun26a-button-beep", title="Jun 26a · Button Beep", folder=SH + "Jun26a_Button_Buzzer", old="sketch_jun26a", board="uno",
         what="The buzzer beeps while you hold the button.",
         parts=[dict(id="btn", type="button", label="Push button"), dict(id="bz", type="buzzer_p", label="Passive buzzer")],
         wires=[("btn", "leg 1", "D13", "button"), ("btn", "leg 2", "GND", "ground"), ("bz", "+", "D12", "beep"), ("bz", "−", "GND", "ground")],
         serial=9600, try_=["Hold the button down."]),
    dict(slug="l-jun26b-button", title="Jun 26b · Button Test", folder=SH + "Jun26b_Button_Serial", old="sketch_jun26b", board="uno",
         what="Prints a message while the button is pressed.", parts=[dict(id="btn", type="button", label="Push button")],
         wires=[("btn", "leg 1", "D13", "button"), ("btn", "leg 2", "GND", "ground")], serial=9600, try_=["Serial Monitor at 9600. Press the button."]),
    dict(slug="l-jun26c-led-patterns", title="Jun 26c · 4 LED Patterns", folder=SH + "Jun26c_LED_4Patterns_Button", old="sketch_jun26c", board="uno",
         what="10 LEDs with 4 patterns. The button changes the pattern.",
         parts=[dict(id="leds", type="ledrow", label="10 LEDs + 10 resistors"), dict(id="bz", type="buzzer_p", label="Passive buzzer"),
                dict(id="btn", type="button", label="Push button")],
         wires=[("leds", str(i - 1), f"D{i}", "LED " + str(i - 1)) for i in range(2, 12)] +
               [("leds", "GND", "GND", "all LED short legs"), ("bz", "+", "D12", "beep"), ("bz", "−", "GND", "ground"),
                ("btn", "leg 1", "D13", "change pattern"), ("btn", "leg 2", "GND", "ground")], serial=9600,
         try_=["Press the button to switch patterns."]),
    dict(slug="l-jul15b-tilt", title="Jul 15b · Tilt Sensor", folder=SH + "Jul15b_MPU6050_TiltDirection", old="sketch_jul15b", board="uno",
         what="Tilt the sensor and it prints LEFT, RIGHT, UP, DOWN or CENTER.", parts=[dict(id="mpu", type="mpu6050", label="Tilt sensor MPU6050")],
         wires=[("mpu", "SDA", "A4", "data (I2C)"), ("mpu", "SCL", "A5", "clock (I2C)"), ("mpu", "VCC", "5V", "power"), ("mpu", "GND", "GND", "ground")],
         serial=9600, try_=["Serial Monitor at 9600. Tilt the sensor in each direction."]),
    dict(slug="l-aug16a-esp32-led", title="Aug 16a · ESP32 Web LED", folder=SH + "Aug16a_ESP32_WiFi_LED_WebAPI", old="sketch_aug16a", board="esp32",
         what="First Wi-Fi project: web addresses /on, /off and /PoP control an LED.", parts=[dict(id="led", type="led", label="LED + 220Ω")],
         wires=[("led", "+", "D23", "on / off"), ("led", "−", "GND", "ground")], serial=9600, secrets=True,
         try_=["Serial Monitor at 9600 shows the IP address. Open <code>http://&lt;IP&gt;/on</code> on a phone."]),
    dict(slug="l-auto-door", title="Automatic Door", folder=SH + "Door_Servo_UltrasonicAutoOpen", old="servodoor12345678910", board="uno",
         what="Walk up to the door (within 20 cm) and it beeps and opens by itself.",
         parts=[dict(id="sv", type="servo", label="Door servo SG90"), dict(id="us", type="hcsr04", label="Distance sensor HC-SR04"),
                dict(id="bz", type="buzzer_a", label="Active buzzer")],
         wires=[("sv", "SIG", "D10", "door angle"), ("sv", "5V", "5V", "power"), ("sv", "GND", "GND", "ground"),
                ("us", "TRIG", "D7", "send sound"), ("us", "ECHO", "D6", "hear echo"), ("us", "VCC", "5V", "power"), ("us", "GND", "GND", "ground"),
                ("bz", "+", "D8", "beeps"), ("bz", "−", "GND", "ground")], serial=9600, libs=["Servo"],
         try_=["Move your hand within 20 cm of the sensor."]),
]
for p in LEARNING:
    p.setdefault("group", "Learning Steps")
    p.setdefault("learn", [])
    p.setdefault("tips", [])

# --------------------------------------------------------------------------
# Python programs (python/)
# --------------------------------------------------------------------------
PY = "python/03_Arduino_ESP32_Companions/"
PYTHON = [
    dict(slug="py-serial-button-keypress", title="Button → Keyboard (Python)", file=PY + "serial_button_to_keypress.py", old="agent.py",
         kind="usb", baud=9600, board_card="button-to-keypress", sketch="Input_Button_SerialEvent",
         what="Listens to the Arduino. When the Arduino's button sends <b>=</b>, this program presses <b>=</b> on the computer keyboard.",
         try_=["Upload <b>Button to Keyboard</b> to the Uno and close the Serial Monitor.",
               "Run this program, open Calculator, type <code>2+2</code>, then press the breadboard button."],
         tips=[("Nothing happens", "Check the COM port in the file (<code>PORT = \"COM5\"</code>) matches Arduino IDE → Tools → Port.", False)]),
    dict(slug="py-esp32-led-control", title="ESP32 LED Web Remote (Python)", file=PY + "web_esp32_led_control.py", old="wificomunication.py",
         kind="wifi", board_card="esp32-wifi-led", sketch="ESP32_WiFi_LED_WebAPI", showcase=True, star=True,
         what="Makes a web page with <b>ON</b>, <b>OFF</b> and <b>BIRD</b> buttons that control the ESP32's LED over Wi-Fi. BIRD keeps it blinking.",
         try_=["Upload <b>ESP32 Wi-Fi LED</b> and note its IP address.", "Put that IP in <code>ESP32_IP = \"...\"</code> at the top of this file.",
               "Run this program and open <code>http://127.0.0.1:5000</code>."],
         tips=[("Buttons do nothing", "The ESP32's IP address changed. Check it in the Serial Monitor.", False)]),
    dict(slug="py-led-slider", title="LED Brightness Slider (Python)", file=PY + "web_led_brightness_slider.py", old="inoledblink.py",
         kind="usb", baud=9600, board_card="led-brightness-web-slider", sketch="LED_Brightness_WebSlider", showcase=True,
         what="A web page with a slider from 0 to 255. Moving it sends the number to the Arduino to set an LED's brightness on pin 11.",
         try_=["Upload <b>LED Brightness from the Web</b> to the Uno, then close the Serial Monitor.",
               "Run this program and open <code>http://127.0.0.1:5000</code>. Move the slider.",
               "Share it: double-click <code>DEMO_LED_from_anywhere_Uno_slider.bat</code>."],
         tips=[("Could not open COM5", "Close the Serial Monitor, plug in the Uno, and set <code>PORT</code> in the file to the COM number in Tools → Port.", False)]),
    dict(slug="py-clock-sender", title="PC Clock Sender (Python)", file=PY + "serial_clock_sender.py", old="clock.py",
         kind="usb", baud=115200, board_card=None, sketch=None,
         what="Sends the computer's time to the Arduino every second, so an Arduino clock can show it.",
         try_=["Plug in the Arduino and run this program. It prints each time it sends."],
         tips=[("Board program missing", "The Arduino clock program was not saved. It's on the to-do list.", True)]),
    dict(slug="py-sensor-reader", title="Sensor Reader (Python)", file=PY + "serial_sensor_reader.py", old="serialreads.py",
         kind="usb", baud=115200, board_card=None, sketch=None,
         what="A lesson on reading temperature and humidity lines from an Arduino. All its code is still commented out.",
         try_=["Read the comments to learn how serial reading works."],
         tips=[("Does nothing yet", "Every line is a comment. Un-comment it when the DHT Arduino program exists.", True)]),
    dict(slug="py-tft-noticeboard", title="TFT Animation & Noticeboard (Python)", file=PY + "web_tft_animation_noticeboard.py", old="animation.py",
         kind="usb", baud=115200, board_card=None, sketch=None,
         what="A web page to pick one of 5 screen animations or send a text message to a colour screen.",
         try_=["Plug in the board with the screen and run this program.", "Open <code>http://127.0.0.1:5000</code>, pick an animation or type a notice."],
         tips=[("Board program missing", "The screen program that understands ANIM and NOTICE was not saved. It's on the to-do list.", True)]),
    dict(slug="py-chirpquest", title="ChirpQuest Bird Guide", file="python/04_ChirpQuest/chirpquest.py", old="Chirpquestbrd.py",
         kind="none", star=True, ngrok=True,
         what="A bird-guide website for kids: 16 North Texas birds, real photos, a checklist, videos, badges, and Pip the Cockatiel who answers questions with AI.",
         try_=["Run the program and open <code>http://127.0.0.1:5000</code>.", "Ask Pip: <i>Why are cardinals red?</i>"],
         tips=[("Pip gives short answers", "No Gemini key found. Copy <code>.env.example</code> to <code>.env</code> and paste the key.", False)]),
    dict(slug="py-pet-care", title="Pet Care Agent", file="python/02_Mini_Projects/PetCareAgent/pet_care_agent_v2.py", old="vetagent.py",
         kind="none",
         what="Call the pet clinic! Talk to a Cat, Dog, Fish or Bird care agent, or ask about opening hours and appointments.",
         try_=["Type <code>123 4567</code> as the number to call.", "Type <code>agent</code>, pick <code>1</code>, then ask about <code>grooming</code>."], tips=[]),
    dict(slug="py-rose-library", title="Rose Library", file="python/02_Mini_Projects/RoseLibrary/library_checkout.py", old="megaprogect.py",
         kind="none", run_in="python/02_Mini_Projects/RoseLibrary",
         what="A library computer: log in with your member ID and check out books.",
         try_=["Enter ID <code>123</code> (Alice).", "Type a title exactly, e.g. <code>Coding Kitty</code>. Type <code>done</code> to finish."], tips=[]),
    dict(slug="py-basics", title="Python Basics (13 lessons)", file="python/01_Python_Basics/", old="basics.py … trycatch.py",
         kind="none", lessons=True,
         what="13 short lessons: print, variables, input, if/else, a calculator, strings, loops, functions, data types and error handling.",
         try_=["Run one lesson at a time, starting with <code>01_hello_print.py</code>."], tips=[]),
]
